export default {
  'text-align': 'left',
  'flex-direction': 'row',
  direction: 'ltr',
  'sideBar-left': 0,
  'sideBar-right': null,
  'mainpage-content-margin': '0 0 0 300px',
  'sideBar-items-border-left': 0,
  'sideBar-items-border-right': '2px solid rgb(56, 132, 255)',
  'sideBar-image-margin': '0 15px 0 0',
  'templates-list-image-margin': '0 10px 0 0',
  'templates-questions-margin': '0 0 0 20px',
  'questions-remove-icon-left': null,
  'questions-remove-icon-right': '20px',
  'users-filter-margin': '0 20px 0 0',
  'users-filter-typesBox-margin': '0 5px 0 0',
  'users-filter-itemIcon-margin': '0 15px 0 0',
  'notify-box-position-left': null,
  'notify-box-position-right': 0,
  'media-uploaded-item-margin': '0 20px 0 0',
  'upsert-form-btn-right': null,
  'upsert-form-btn-left': '15px',
  'forms-skeleton-margin': '0 10px 20px 0',
  column: '0 10px 0 0',
  'upsert-form-design-select-margin': '0 5px 0 0',
  'datetime-range-margin': '0 20px 0 0'
}
