export default {
  'text-align': 'right',
  'flex-direction': 'row-reverse',
  direction: 'rtl',
  'sideBar-left': null,
  'sideBar-right': 0,
  'mainpage-content-margin': '0 300px 0 0',
  'sideBar-items-border-right': 0,
  'sideBar-items-border-left': '2px solid rgb(56, 132, 255)',
  'sideBar-image-margin': '0 0 0 15px',
  'templates-list-image-margin': '0 0 0 10px',
  'templates-questions-margin': '0 20px 0 0',
  'questions-remove-icon-left': '20px',
  'questions-remove-icon-right': null,
  'users-filter-margin': '0 0 0 20px',
  'users-filter-typesBox-margin': '0 0px 0 5px',
  'users-filter-itemIcon-margin': '0 0px 0 15px',
  'notify-box-position-left': 0,
  'notify-box-position-right': null,
  'media-uploaded-item-margin': '0 0 0 20px',
  'upsert-form-btn-right': '15px',
  'upsert-form-btn-left': null,
  'forms-skeleton-margin': '0 0 20px 10px',
  column: '0 0 0 10px',
  'upsert-form-design-select-margin': '0 0 0 5px',
  'datetime-range-margin': '0 0 0 20px'
}
